name: build

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-14
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - name: ubuntu install
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install ninja-build git clang python3 -y
      - name: macos install
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install ninja
      - name: build-${{ matrix.target }}
        shell: "bash"
        run: |
          bash build.sh ${{ matrix.target }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: primjs-${{ matrix.target }}
          path: ./primjs-${{ matrix.target }}.tar.gz
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: primjs
          pattern: primjs*
          merge-multiple: true

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "primjs/*.tar.gz"
